platform :ios, '7.0' 

target 'OnlineRetailerFrameWork' do

pod 'UMengUShare/Social/Sina'
pod 'UMengUShare/Social/WeChat'
pod 'UMengUShare/Social/QQ'
pod 'UMengAnalytics'
pod 'ReactiveCocoa',  '~> 2.4.7’
end
